# Generated by Django 4.0.4 on 2022-04-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_post_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
